name: Send Proxies to Telegram

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run proxy script
        env:
          BOT_TOKEN: ${{ 7171638404:AAGsiMFdwvhXZQMRrzY_XCrsEv9zURBSNEU }}
          SOURCE_CHANNEL: ${{ @ProxyMTProto }}
          TARGET_CHANNEL: ${{ @proxy_who }}
        run: php proxy.php
